- Classes/Controller/WizardContentController.php
- Classes/Controller/WizardController.php
- Classes/Controller/WizardPageController.php
- Classes/Fluid/FluidTemplateContentObject.php
- Classes/Utility/MaskUtility.php
- ext_localconf.php
Some minor patches to make this extension generally usable under TYPO3 CMS 7.x (tested with 7.2). But still, the backend module doesn't really look nice ... ;)
> Compatibility with TYPO3 CMS 7.x

- Resources/Private/Backend/Templates/WizardContent/List.html
- Resources/Private/Backend/Templates/WizardPage/List.html
- Resources/Private/Language/locallang.xlf
Use 'Save and close' which is used more in the core
> [TASK] Change wording of save and exit

- Resources/Public/Scripts/scripts.js
Just a suggestion for backend field handling
> [TASK] Allow only alphanumeric characters for fieldkey

- Classes/Helper/InlineHelper.php
Correct version management for IRRE in backend workspace for page mode display and frontend workspace previous mode
> [FIX] Workspace issues fixing

- Classes/Helper/FieldHelper.php
The field is checked correctly if it is a link field
> [BUGFIX] link field do not become text field after repening, resolves #122

- Classes/Helper/FieldHelper.php
fix via null coalescing operator
> Prevent warning if array is null

- Classes/CodeGenerator/SqlCodeGenerator.php
- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/Controller/WizardContentController.php
- Classes/Controller/WizardController.php
- Classes/Domain/Model/Page.php
- Classes/Domain/Repository/BackendLayoutRepository.php
- Classes/Domain/Repository/ContentRepository.php
- Classes/Domain/Repository/StorageRepository.php
- Classes/Helper/FieldHelper.php
- Classes/Hooks/PageLayoutViewDrawItem.php
- Classes/Utility/GeneralUtility.php
- Classes/ViewHelpers/EditLinkViewHelper.php
- ext_localconf.php
Replace all boolean occurrences by lowercased spelling
> Streamline boolean spelling to adhere to PSR-2

- Classes/Domain/Repository/StorageRepository.php
> [FEATURE] Support EXT: prefix for json configuration

- Classes/Helper/InlineHelper.php
Fix bug that backend preview error on translation described in #88 and #138 with solution described in #88 by @Gernott.
> :bug: Fix localized backend preview

- Classes/CodeGenerator/TyposcriptCodeGenerator.php
- Classes/Controller/WizardController.php
- Classes/Hooks/PageLayoutViewDrawItem.php
- Classes/ViewHelpers/LinkViewHelper.php
> [TASK] Use underscoredToUpperCamelCase instead of ucfirst

- Classes/Domain/Repository/StorageRepository.php
Very simple fix for Issue #210. 
https://github.com/Gernott/mask/issues/210
> Fixed Issue #210

- composer.json
Set requirements to the release version of TYPO3
> Require TYPO3 10 release version

- Resources/Public/Styles/styles.css
Adds a background for tooltip so that it's better visible
> Highlight tooltip for more clarity

- Classes/ItemsProcFuncs/CTypeList.php
> [BUGFIX] Decode json config in CTypeList->itemsProcFunc

- ext_localconf.php
Remove unused variables and fix undeclared variable
"json".
> [BUGFIX] Fix ext_localconf.php

- Classes/CodeGenerator/SqlCodeGenerator.php
- Configuration/Services.yaml
- ext_localconf.php
Replace signal slot with psr-14 event.
> [TASK] Use psr-14 events

- Classes/Domain/Repository/StorageRepository.php
When creating an inline (repeating) field in mask, a new table
definition is being generated in mask.json. If one later decides to
remove this inline field, an empty table definition is still there.
Although the database analyzer removes this table, exceptions are
raised when working with an existing content element, because there are
tca configurations for a non existing table.
Resolves: #265
Resolves: #255
Resolves: #272
> [BUGFIX] Remove table definition of inline fields completely

- Resources/Public/Scripts/scripts.js
The response object was changed in TYPO3 v9. Adjust the check
accordingly.
> [BUGFIX] Fix key validation in frontend

- Classes/Helper/InlineHelper.php
Add check for _PAGES_OVERLAY_UID if dealing with page records.
Resolves: #258
> [BUGFIX] Fix translations of inline fields in backend layout

- Classes/CodeGenerator/SqlCodeGenerator.php
- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/CodeGenerator/TyposcriptCodeGenerator.php
- Classes/Helper/FieldHelper.php
- Classes/Utility/GeneralUtility.php
- Configuration/TCA/Overrides/pages.php
- Configuration/TCA/Overrides/tt_content.php
- Tests/Unit/CodeGenerator/TcaCodeGeneratorTest.php
- Tests/Unit/GeneralUtilityTest.php
- Tests/Unit/Helper/FieldHelperTest.php
- ext_localconf.php
- ext_tables.php
This pull requests adds tests for all tca codegenerator methods.
There was some refactoring needed to make them suitable for tests.
There is also a bugfix for a previous merge included regarding labels on page records.
Adds feature to make elements searchable in global search.
> Test tca codegenerator

- Classes/ExpressionLanguage/MaskFunctionsProvider.php
> [BUGFIX] Match inline tt_content records having mask element as default

- Classes/ViewHelpers/TcaViewHelper.php
Some control fields and fields in other tabs can not be selected
anymore. This prevents unintended use of these fields.
If one of these fields was selected already, they will still work, but
it is advised to migrate them to a custom field.
Fixes: #257
> [BUGFIX] Only show existing fields that are not used otherwise

- Classes/Helper/FieldHelper.php
- Tests/Unit/Helper/FieldHelperTest.php
If elementKey is not empty, the element must match.
> [BUGFIX] Fix getFieldType method if elementKey is set

- Classes/Helper/InlineHelper.php
Add possibility to filter out restricted (fe_group) repeating items to $queryBuilder
> [TASK] Add FrontendGroupRestriction to InlineHelper

- .gitignore
- .vscode/settings.json
- Documentation/Guides/CropVariants.rst
- Documentation/Guides/Index.rst
- Documentation/Guides/RTEConfig.rst
- Documentation/Settings.cfg
@nhovratov as discussed on slack. Please correct – I haven't edited an RST file before hope it's not too bad
> Proposal for Guides regarding crop variants and rte config

- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/CodeGenerator/TyposcriptCodeGenerator.php
- Classes/Controller/FieldsController.php
- Classes/Domain/Repository/StorageRepository.php
- Classes/ExpressionLanguage/MaskFunctionsProvider.php
- Classes/Utility/ArrayToTypoScriptConverter.php
- Classes/Utility/TcaConverter.php
- Configuration/Mask/Tabs/select.php
- Configuration/Mask/TcaFields.php
- Configuration/TCA/Overrides/tt_content.php
- Resources/Private/Language/locallang.xlf
- Tests/Unit/CodeGenerator/TcaCodeGeneratorTest.php
- Tests/Unit/Domain/Repository/StorageRepositoryTest.php
- Tests/Unit/StorageRepositoryCreatorTrait.php
- Tests/Unit/Utility/TcaConverterUtilityTest.php
- ext_localconf.php
- ext_tables.php
this commit add the selecticon option to selectboxes in the tab File in mask backend
https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectSingle.html#select-foreign-rows-with-icons
> [FEATURE] add selectIcon option to field selectbox

- Resources/Public/JavaScript/Mask.js
This pull request fixed this issue
[https://github.com/Gernott/mask/projects/1#card-72314478](https://github.com/Gernott/mask/projects/1#card-72314478)
> [BUGFIX] Fields in the palette of an inline field can't be dragged out of the palette

- Classes/CodeGenerator/HtmlCodeGenerator.php
- Classes/Helper/InlineHelper.php
This pull request added this feature request [https://github.com/Gernott/mask/projects/1#card-59262538](https://github.com/Gernott/mask/projects/1#card-59262538)
> [FEATURE] Resolve multi selections

- Classes/Loader/JsonSplitLoader.php
- Tests/Unit/Fixtures/Configuration/ContentElements/e.json
- Tests/Unit/Loader/JsonSplitLoaderTest.php
this comment fixes a bug which prevents to have inline fields in inline fields
> [BUGFIX] nested inline fields, lose their child fields

- Documentation/Settings.cfg
- update copyright year
- include footer links to the TER page for installation and contact
to conveniently guide the reader to all aspects of the extension
> [DOCS] Update Settings.cfg

- Classes/Controller/AjaxController.php
- Configuration/Backend/AjaxRoutes.php
- Configuration/Mask/Tabs/select.php
- Configuration/Mask/TcaFields.php
- Resources/Public/JavaScript/Components/FormField.js
- Resources/Public/JavaScript/Mask.js
> [FEATURE] Prefill tables for foreign_table field

- Classes/Updates/ConvertTemplatesToUppercase.php
If the directories don't exist yet, there can be an exception which should be handled
> [BUGFIX] Catch exception in update wizards

- Classes/Imaging/PreviewIconResolver.php
> [BUGFIX] Handle ResourceDoesNotExistException in PreviewIconResolver

- Classes/Helper/InlineHelper.php
> [BUGFIX] Properly resolve nested IRRE elements of type content

- Classes/Controller/AjaxController.php
Upgrading a project showed me a notice which makes the backend not loading because of the notice/exception.
> [BUGFIX] Avoid notice

- Classes/Controller/AjaxController.php
- Classes/Event/MaskAfterElementDeletedEvent.php
- Tests/Unit/Event/MaskAfterElementDeletedEventTest.php
Adds an event that is sent after an element is deleted.
> added MaskAfterElementDeletedEvent

- Documentation/Contentelements/Index.rst
https://github.com/Gernott/mask/issues/551
> [DOC] Mention FontAwesome icon bug in New Content Element Wizard

- Configuration/Sets/Mask/config.yaml
- Configuration/Sets/Mask/setup.typoscript
- Documentation/Installation/Index.rst
- Documentation/Installation/_codesnippets/_config.yaml
Used as TypoScript provider
References https://github.com/Gernott/mask/issues/639
> [TASK] Introduce a site set

- .github/workflows/tests.yaml
- Classes/CodeGenerator/TcaCodeGenerator.php
> Add PHP 8.4 support

- Classes/Updates/ConvertTemplatesToUppercase.php
- Classes/Updates/FillTranslationSourceField.php
- Classes/Updates/MigrateContentFields.php
- Classes/Updates/MoveRteOptions.php
- ext_localconf.php
Hi @nhovratov 
As we discussed through Slack, please see the PR which contains Upgrade Wizard Registration Fix in v13. Please check and adapt to the main version.
Thank you.
> Upgrade Wizard Registration Fix
