- Classes/ViewHelpers/TranslateLabelViewHelper.php
- Resources/Private/Backend/Partials/Forms/General/Form.html
- Resources/Private/Backend/Partials/Forms/General/Inline.html
- Resources/Private/Backend/Templates/WizardContent/Edit.html
- Resources/Private/Backend/Templates/WizardPage/Edit.html
Hallo Gernott,
ich habe gerade einen Patch für diese Extension erstellt. Generell übersetzt dieser die Labels im Backend-Modul, wenn diese ein Language-Label sind. Zudem wird das Label und der Key gekürzt, so das man auf meinen kleinen Laptop-Monitor noch arbeiten kann. :)
Beste Grüße,
Fabi
> [FEATURE] Crops and translates the language labels in the backend module

- Classes/CodeGenerator/TyposcriptCodeGenerator.php
- ext_localconf.php
To set a label of a field depending in a CType no user function is needed. This can be done with pure TypoScript. The patch sets the needed TypoScript and removes the superfluous user function.
> [TASK] Use TypoScript to define field label

- Classes/Controller/FrontendController.php
Since `$this->view->setPartialRootPaths(array($partialRootPath));` and `$this->view->setLayoutRootPaths(array($layoutRootPath));` is overriding whatever is defined in `plugin.tx_mask.view` we have to combine the array with the value that is set in extension settings. Otherwise it's not possible to set other rootPaths then the one in the extension settings.
> [BUGFIX] Fix overriding of partialRootPaths and layoutRootPaths

- composer.json
- ext_emconf.php
With this it' easier to test extension with TYPO3 8 dev-master
in an TYPO3 composer instance.
Resolves: https://forge.typo3.org/issues/77940
> [TASK] Remove version restriction for TYPO3 core

- Resources/Private/Backend/Partials/Forms/Config/RteTransform.html
- Resources/Private/Backend/Partials/Forms/Eval/Alpha.html
- Resources/Private/Backend/Partials/Forms/Eval/AlphaNum.html
- Resources/Private/Backend/Partials/Forms/Eval/AlphaNumX.html
- Resources/Private/Backend/Partials/Forms/Eval/Domainname.html
- Resources/Private/Backend/Partials/Forms/Eval/Email.html
- Resources/Private/Backend/Partials/Forms/Eval/Lower.html
- Resources/Private/Backend/Partials/Forms/Eval/Md5.html
- Resources/Private/Backend/Partials/Forms/Eval/NoSpace.html
- Resources/Private/Backend/Partials/Forms/Eval/Null.html
- Resources/Private/Backend/Partials/Forms/Eval/Num.html
- Resources/Private/Backend/Partials/Forms/Eval/Password.html
- Resources/Private/Backend/Partials/Forms/Eval/Required.html
- Resources/Private/Backend/Partials/Forms/Eval/Time.html
- Resources/Private/Backend/Partials/Forms/Eval/TimeSec.html
- Resources/Private/Backend/Partials/Forms/Eval/Trim.html
- Resources/Private/Backend/Partials/Forms/Eval/Unique.html
- Resources/Private/Backend/Partials/Forms/Eval/UniqueInPid.html
- Resources/Private/Backend/Partials/Forms/Eval/Upper.html
- Resources/Private/Backend/Partials/Forms/Eval/Year.html
- Resources/Private/Backend/Partials/Forms/Fields/Link/Tabs.html
- Resources/Private/Backend/Partials/Forms/Fields/Richtext/Tabs.html
- Resources/Private/Backend/Partials/Forms/Fields/Text/Tabs.html
- Resources/Private/Backend/Partials/Forms/General/RenderFieldContent.html
- Resources/Private/Backend/Templates/WizardContent/Edit.html
- Resources/Private/Backend/Templates/WizardPage/Edit.html
As the field variable within fluid templates is an array, it cannot be
used as string. This currently results in a fatal error, because
htmlspecialchars on an array cannot be applied.
> [BUGFIX] Fix fluid templates for TYPO3 8

- Classes/Utility/GeneralUtility.php
- Resources/Public/Scripts/scripts.js
This patch allows to define empty items for fields with items
configuration. This is useful for e.g. selectbox fields as the first
value may be empty to not force any default value.
Furthermore the JavaScript is changed to set the current line number
(key) for items if no value is defined. This is allows to only define
the labels in an items field and use the line numbers as their values.
> Enhance selectbox handling

- Resources/Private/Backend/Partials/Forms/Fields/Datetime/Default.html
Setting default values for datetime fields is bound to the MySQL server
configuration. To be compatible to the default settings, this patch
removes default values for those fields.
> [BUGFIX] Prevent SQL default value for datetime fields

- Classes/ViewHelpers/LinkViewHelper.php
To be compatible with standalone fluid in TYPO3 8 we need to turn of the default
html ecaping.
> [BUGFIX] Prevent html escaping in \MASK\Mask\ViewHelpers\LinkViewHelper

- Classes/Domain/Model/Content.php
- Classes/Domain/Model/Page.php
- Classes/Helper/InlineHelper.php
- Documentation/ChangeLog/Index.rst
- Documentation/Index.rst
- composer.json
- ext_emconf.php
You need to ensure that $uid is a valid integer. If it is not given (e.g. when rendering a FluidTemplate outside of a content element scope), the call in line 90 `$fileRepository->findByRelation($table, $fieldKey, $uid);` throws an exception.
> [BUGFIX] Fixed missing $uid validation check

- Resources/Private/Backend/Partials/Forms/Config/Behaviour/LocalizationMode.html
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
localizationMode is deprecated and doesn't work in typo3 8.
it would be better to use l10n_mode (copy, prefixLangTitle, exclude) like in my example above.
this option could be activated for any content.
what do you think about this?
> use l10n_mode instead of localizationMode

- Classes/Controller/WizardController.php
- Resources/Private/Backend/Templates/WizardContent/List.html
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
This patch triggers an automated cache clearing to enforce TCA
generation. The information alert in the list overview is removed.
> [FEATURE] Enforce cache clearing in save process

- Classes/Domain/Repository/StorageRepository.php
If you choose to use an existing field previously defined in mask itself
and not set an own label, the field in the edit form has no label at all.
This patch uses the label if the first usage of the field to ensure an
existing label.
> [BUGFIX] Re-use label from existing mask field

- Classes/Helper/FieldHelper.php
- Classes/ViewHelpers/TcaViewHelper.php
This patch allows the reuse of previously defined tab fields. As the
"Tab" type is not a valid TCA type, no column is found. Instead
mask should use its own storage for lookup,
Furthermore for tables other than tt_content, only mask columns are
allowed. To find proper columns, on storage information can be used too.
> [BUGFIX] Allow reuse of tab fields

- Classes/Domain/Repository/StorageRepository.php
I've already tested this on an affected site. This bug is specific to PHP7.2, as far as I know.
> Added array check before count, fixes #83576

- Documentation/ToDoList/Index.rst
- README.md
- composer.json
Simple PR - Just replaces all links to Forge with GitHub.
> Replace forge links

- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/Utility/GeneralUtility.php
The fileUploadAllowed TCA option currently is ignored due to its value being the string "false" instead of an expected boolean value.
Also correcting this issue needs fixing of GeneralUtility::removeBlankOptions().
> [Fix] fileUploadAllowed TCA handling

- Classes/Controller/WizardController.php
Define `$messages` as array (and name it messages) in `checkFolders()`. Fixes #132
> [BUGFIX] Define default return value as empty array in checkFolders()

- composer.json
The version does not have to be specified in the file (anymore). It's easier to
omit the version field in composer.json. Packagist parses versions from tags
and branch names. New versions of your package are automatically fetched.
Tag/version names should match 'X.Y.Z', or 'vX.Y.Z', with an optional suffix for
RC, beta, alpha or patch versions. So it's fully ok to keep the prefixed "v1.2.3"
syntax.
> [TASK] composer.json: remove version field and use branch-alias

- Classes/Hooks/PageLayoutViewDrawItem.php
Custom backend templates are shown below a header with the elements name. Usually this header is linked to its edit form. This PR does exactly that.
> [No-Brainer] Link backend header of element to its edit page

- Classes/Domain/Repository/StorageRepository.php
Sorting the JSON avoids merge conflicts and results in a more consistent and idempotent output.
> Sort complete JSON structure before it is saved to disk

- Classes/Imaging/IconProvider/ContentElementIconProvider.php
On fully localized systems there can be umlauts as the first character and thus there is the typical question mark instead of the first letter.
> Use mb_substr instead of substr

- CHANGELOG
Quoting keepachangelog.com:
> # keep a changelog
> Don’t let your friends dump git logs into changelogs.
>
> ## What is a changelog? 
>  A changelog is a file which contains a curated, chronologically ordered list of notable changes for each version of a project.
>
> ## Why keep a changelog? 
> To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project. 
>
> ## Who needs a changelog?
>  People do. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how. 
See http://keepachangelog.com/en/1.0.0/ for more information.
For the new changelog I added already changes made after `3.3.1`.
> Keep a changelog

- Classes/CodeGenerator/TcaCodeGenerator.php
Bug: labels of core fields were not displayed in the BE forms for mask tables.
The core package `lang` has been removed in version 9.4 (see also https://forge.typo3.org/issues/84680). The `.xlf` files moved to the `core` package. This updates all references in the TcaCodeGenerator.
> Fix core TCA language file references for TYPO3 9.4.0

- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/Controller/WizardController.php
- Classes/Domain/Repository/StorageRepository.php
- Resources/Public/Scripts/scripts.js
The drag & drop operaiton in the backend re-orders the form elements,
such that the iteration in the Mask storage update is in the correct
order, but that order is destroyed by sortJson. This fixed sorting is
valuable to version control, so instead this commit introduces an extra
field 'order' in the column of the inline type. This is used in the TCA
generator and before the backend view renders.
Additionally, I removed a superfluous initSortable call in the backend JavaScript.
The sortable widget has already been initialized, no need to re-initialize it
with some new functions that do exactly the same.
> Fix sorting of fields in an inline type

- Resources/Private/Backend/Partials/Forms/Fields/Check/Default.html
If the renderType "default" is used, TYPO3 v9.5.0 displays an error message when it renders the backend form.
The checkbox field type is the only instance of the renderType "default" being explicitly set.
> Change default renderType value for checkboxes to the empty string

- ext_localconf.php
The default query restrictions in TYPO3 hide pages and content elements
that are hidden, or that have starttime and/or endtime set, and the
current time is outside of that time frame.
Mask uses a custom TSConfig conditional function that checks the
database for CType in case of tt_content, or backend_layout in case of
pages, to insert its own extended fields (pages) or set overridden
labels for inputs (tt_content).
This also adds a small static cache for the CType check to avoid
querying the database for each TSConfig conditional.
Fixes #203
> Fix TSConfig conditionals for hidden pages and content elements

- Resources/Private/Backend/Partials/Forms/Fields/Date/Default.html
'0000-00-00' is not a valid default value for a date field. This causes the Install Tool to fail when executing a database compare.
Instead, just default to NULL
According to the MySQL Manual: […] The supported range is '1000-01-01' to '9999-12-31’. […]
See: https://dev.mysql.com/doc/refman/5.7/en/datetime.html
> [BUGFIX] Fix invalid default value of date field

- Classes/Controller/WizardContentController.php
- Classes/Controller/WizardController.php
Description
Resolves Issue #185 https://github.com/Gernott/mask/issues/185 where directory creation didn't respect EXT:key
> [BUGFIX] Set Path of content and preview directory if not exist

- Classes/CodeGenerator/SqlCodeGenerator.php
To speed up database queries an own index for each parent field is added to tt_content table.
> Add indexes to tt_content for parent fields

- Classes/Helper/InlineHelper.php
For a faster overview you can view also the hidden sub datasets in the Backend Fluid Templates for each content element.
> Makes hidden IRRE elements visible in the Backend

- Resources/Private/Backend/Partials/Forms/Fields/Richtext/Default.html
Add softref-config to mask-json for Richtext-Fields.
I think this is the better solution than my last PR.
> Enable softref f. Richtext-Fields in mask.json

- Classes/Controller/WizardController.php
The second argument for backend routes has been deprecated since v9.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/58190/
Resolves: #293
> [BUGFIX] Remove deprecated second argument for backend routes

- Classes/CodeGenerator/HtmlCodeGenerator.php
This is the default value for f:format.html
> Remove parseFuncTSPath="lib.parseFunc_RTE" in f:format.html

- CHANGELOG.md
- Classes/CodeGenerator/TcaCodeGenerator.php
- Resources/Private/Backend/Partials/Forms/Fields/Richtext/Default.html
In TYPO3 v10 the order was changed in which richtext configuration is
overridden. Tca now has precedence over RTE.default.preset. Remove the
explicit setting of richtextConfiguration as default as this is the
default anyway.
Note: It is necessary to save the mask elements which have richtext
fields in order to apply this change.
Resolves: #284
Resolves: #281
> [TASK] Remove setting the richtextConfiguration to default in tca

- Resources/Private/Language/locallang.xlf
For security reasons html is not allowed in modals.
Resolves: #233
> [BUGFIX] Remove html in confirmation dialog

- Classes/CodeGenerator/AbstractCodeGenerator.php
- Classes/CodeGenerator/TcaCodeGenerator.php
- Classes/CodeGenerator/TyposcriptCodeGenerator.php
- Classes/Domain/Repository/StorageRepository.php
- Classes/ExpressionLanguage/MaskFunctionsProvider.php
- Classes/Form/FormDataProvider/TcaTypesShowitemMaskBeLayoutFields.php
- Classes/Helper/FieldHelper.php
- Configuration/TCA/Overrides/pages.php
- Tests/Unit/CodeGenerator/TcaCodeGeneratorTest.php
- ext_localconf.php
The problem was that the order of showitem was taken from the mask tca
array instead of columns. This was necessary because backend layouts
can share fields and the order may vary. Now, instead of creating the
whole showitem string for all fields, we extend the showitem for the
specific page type and backend layout just before the tca is processed
with the help of a FormDataProvider. This way it is possible to use the
predefined order of fields and tabs.
Resolves: #214
> [BUGFIX] Fix order of fields and tabs defined for backend layouts

- Classes/Form/FormDataProvider/TcaTypesShowitemMaskBeLayoutFields.php
Mon, 10 Aug 2020 10:37:15 +0000 [ERROR] request="beca54c9e278a" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"maskBeLayout(default)"}
(PHP 7.4.9, TYPO3 10.4.6)
> [BUGFIX] Add single quotes to Typoscript condition

- Classes/Controller/WizardController.php
To avoid naming conflicts, it is not allowed to have Content fields
with the same key, even if they are located in repeating fields.
Fixes: #199
> [BUGFIX] Do not allow having Content fields with same key

- Classes/ViewHelpers/TranslateLabelViewHelper.php
Key might not be a string but return type forces it to be one, so do a type cast
> [BUGFIX] Cast return value to string

- Classes/Helper/InlineHelper.php
In a project (11.5.x-dev, PHP 8.1) the GLOBALS['BE_USER'] object is unset in the frontend request resulting in a PHP error message when calling the frontend with mask inline elements. In newer TYPO3 versions, the corresponding properties ('workspace' in this case) should be fetched from the Context API. That's what the change does.
> [BUGFIX] Fetch workspace ID from context API

- Classes/Controller/AjaxController.php
- Classes/Event/MaskAllowedFieldsEvent.php
- Documentation/Guides/Index.rst
- Documentation/Guides/UseExistingTCAFields.rst
- Tests/Unit/Event/MaskAllowedFieldsEventTest.php
With this it is possible to use already existing TCA fields in a Mask content element, by extending the "Core fields" list.
This solves issue #534
> [FEATURE] Add a PSR-14 event to manipulate data in the $allowedFields array

- Classes/EventListeners/MaskBackendPreviewEventListener.php
Without the request on the rendering context, the uri.editRecord and link.editRecord ViewHelpers of the backend module are unable to automatically generate a returnUrl.
In the case of uri.editRecord we get an exception in the page module, and with the link.editRecord we'll end up on a blank page, when trying to use the close button to return to the previous page.
---
Not sure if there is a better way to get the TYPO3_REQUEST than through $GLOBALS. Maybe injection?
Also not sure if that perhaps is more of a TYPO3 core bug.
Anyway, I encountered this, because I like to add direct links to nested Content Elements if present right in the Page Module.
An example preview template taken from an Accordion Element:
```html
<f:if condition="{data.tx_mask_accordion}">
<f:for …
```
> [BUGFIX] Prevent error when be:uri.editRecord is used in preview template

- Classes/CodeGenerator/TcaCodeGenerator.php
- Tests/Unit/CodeGenerator/TcaCodeGeneratorTest.php
This allows ext:linkvalidator to properly detect inputLink fields.
Fixes #555
> [BUGFIX] Add softref-config to link fields

- Classes/CodeGenerator/TcaCodeGenerator.php
The correct name of the "transOrigPointerField" is "l10n_parent", but the palette uses the wrong field name "l18n_parent"
> [BUGFIX] Show correct field "l10n_parent" in language palette

- Configuration/Mask/Tabs/richtext.php
With this commit it is possible to enable or disable the required validation for rich text editor fields.
> enabled required validation for rich text editor fields

- Documentation/BackendPreview/Index.rst
See https://github.com/Gernott/mask/issues/551#issuecomment-1854206592
> [DOCS] Document clearing local storage when icon is not showing up

- Classes/Imaging/PreviewIconResolver.php
> [TASK] get icon with PathUtility instead of ResourceFactory

- Configuration/TCA/Overrides/tt_content.php
Fixes #669
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85489
> [BUGFIX] Remove application of extendBodytextSearchAndWhere in TYPO3 version 13.4.5 and onwards.

- Classes/Utility/FieldTypeUtility.php
Ensure that isMediaType is capable of managing the `allowed` configuration of a media field in array and string notation to prevent exceptions for type errors.
> [FIX] Make allowed TCA config also possible in array notation.
